### ISSUE TITLE
Replacement for X-editable? 

### ISSUE THREAD

**Issue by vincentwhales** [pallets-eco/flask-admin#1615]
It seems like this plugin hasn't had any development for a while. In addition, it doesn't work for Many-to-Many relationship. 

Are there other alternatives?

**Comment by ljluestc** [comment]
```

from flask import Flask
from flask_mongoengine import MongoEngine
from flask_mongoengine.wtf import orm

app = Flask(__name__)
app.config['MONGODB_SETTINGS'] = {
    'db': 'your_db_name',
    'host': 'your_mongodb_uri'
}
db = MongoEngine(app)

# Define Author model
class Author(db.Document):
    name = db.StringField(required=True)

# Define Book model
class Book(db.Document):
    title = db.StringField(required=True)
    authors = db.ListField(db.ReferenceField(Author))

# Register Many-to-Many relationship
authorship = db.DynamicDocument.get_collection("authorship")
authorship.insert_one({"Title":"Jurassic Park"," authors":[{"name":" John Doe"},{"name":" Jane Roe"} ])
```

**Comment by hasansezertasan** [comment]
I believe the problem with X-Editable remains. It didn't get any updates for a couple of years now and it doesn't support Bootstrap5 and Tabler.

I could recommend HTMX for such a small feature but it'll require some work to be done on the backend.

HTMX could also eliminate some JS scripts used for update, create and detail modals, which will result in less frontend code to maintain.

Flask Admin could also use HTMX for deletions and prevent full page reload after deletion. Here is my take: why reload the list view after deleting a single item instead of removing that item (row) from the HTML table?
