### ISSUE TITLE
Move from flask-babelex to flask-babel

### ISSUE THREAD

**Issue by demetrius-mp** [pallets-eco/flask-admin#2165]
Since flask-babelex is discontinued, it would be great to add support for flask-babel instead of babelex in flask admin.

**Comment by gunlinux** [comment]
Started to work with migration, got some issue with testing and app context

**Comment by LeXofLeviafan** [comment]
Related items:
* #2077
* #2270 
* #2288 

Additionally, there's currently a bug which prevents flask-admin (the latest PyPI package) from working with `flask-babelex` when `flask-babel` is installed: trying to open an entry edit form results in `AttributeError: 'Babel' object has no attribute 'locale_selector'` (`wtforms` imports `flask_wtf` [that uses `flask_babel`](https://github.com/wtforms/flask-wtf/blob/v1.1.1/src/flask_wtf/i18n.py#L4), which clearly picks up the instance produced by `flask-babelex` and [fails to use it](https://github.com/python-babel/flask-babel/blob/master/flask_babel/__init__.py#L259) because it [relies on a decorator to specify the locale-selector](https://pythonhosted.org/Flask-BabelEx/#configuration) instead of [a keyword argument](https://python-babel.github.io/flask-babel/index.html#configuration)). And yes, it works when `flask-babel` is _not_ installed due to [how `flask-wtf` handles it](https://github.com/wtforms/flask-wtf/blob/v1.1.1/src/flask_wtf/form.py#L14-L17).

…When's the next release anyway? The latest version on PyPI is 1.6.0 which is over a year old by now, and it doesn't include `flask-babel` fallback support (since it was added merely _half a year_ ago).

**Comment by samuelhwilliams** [comment]
This has been done by https://github.com/pallets-eco/flask-admin/issues/2447 now - will be released in [v2.0.0](https://github.com/pallets-eco/flask-admin/issues/2451) 🙏
