### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

### ISSUE THREAD

**Issue by pankus** [pallets-eco/flask-admin#2375]
https://github.com/flask-admin/flask-admin/blob/896fca64f7eb7970bb5775c2c9ff6b3a07c9de4a/flask_admin/form/upload.py#L467C21-L467C21

ANTIALIAS was removed in Pillow 10.0.0 (after being deprecated through many previous versions). Now you need to use PIL.Image.LANCZOS or PIL.Image.Resampling.LANCZOS. [https://stackoverflow.com/a/76616129/5541592](url)

Line 467 must be corrected. Even better, I presume, if a user can manage the compression type using some user-defined parameter.

**Comment by skwzrd** [comment]
Seems like this was fixed on the master branch (currently version 1.6.1),
https://github.com/flask-admin/flask-admin/blob/14e24c970f0ee3a29add830612eee9a0b0ba5dcc/flask_admin/form/upload.py#L464

And here is the commit https://github.com/flask-admin/flask-admin/commit/96b92deef8b087e86a9dc3e84381d254ea5c0342

**Comment by urshulgi** [comment]
> Seems like this was fixed on the master branch (currently version 1.6.1),

Maybe I'm wrong but I can see the commit and this is from August 9, 2023:
![image](https://github.com/flask-admin/flask-admin/assets/24327796/636ef449-ebb8-43ba-bf03-c70ae568e41f)

And the version was released June 19:
![image](https://github.com/flask-admin/flask-admin/assets/24327796/b21bf7a0-e506-4f58-b8dc-4cc728e2bcda)

So the fix was added two months later?

And another thing, I can see 1.6.1 being on a different date on pypi, February 20 (Which matches the tag build):
![image](https://github.com/flask-admin/flask-admin/assets/24327796/692db798-d332-4d4f-8478-4d6210eb2059)

I just downloaded the source code that is attached to the release here on GH for 1.6.1 and still can see ANTIALIAS:
![image](https://github.com/flask-admin/flask-admin/assets/24327796/9a29f259-d7f4-4122-9089-5a1527b8e078)

And I have got the error despite reinstalling the library a few times:
![image](https://github.com/flask-admin/flask-admin/assets/24327796/5361bb00-a65d-4ff8-8808-eec75f902416)

**Comment by samuelhwilliams** [comment]
You're right - it looks like this change hasn't been released yet. This project has just been transferred under to the [pallets ecosysytem](https://github.com/pallets-eco) project, so hopefully we can get a release lined up shortly, but we have some admin to take care of first.
