### ISSUE TITLE
Mirror Pallets-eco setup for projects

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [pallets-eco/flask-admin#2435]
@samuelhwilliams working on it.

**Comment by samuelhwilliams** [comment]
I'm starting work on this in a branch/PR on my fork: https://github.com/samuelhwilliams/flask-admin/pull/1.

Going to just dump some notes here as I work through it - please bear with as a bunch of this will be stuff I haven't touched before.

I'm using `Flask-SQLAlchemy` as the reference project in terms of files/structure to copy, etc.

* I've migrated `requirements-dev.txt` to `requirements/tests.in`, and not pip-compiled that to a `tests.txt` because I think each Python version tox runs the tests in needs to pick appropriate versions internally - there's not a single set of dependencies that I think we can freeze that would work for all python versions we're matrix testing.
* `flask-sqlalchemy` has a `docs` directory, `flask-admin` has a `doc` directory. I'm not migrating these files because it's a huge changeset. We can do it in a separate PR if we thing it's worth doing.
  * The docs also need updating to the Pallets theme; possibly some fairly chunky changes needed to do this? I think it's best to do this separately.
* `flask-sqlalchemy` has a `main` branch; `flask-admin` is still using a `master` branch.
* I've copied across the `typing` target from `flask-sqlalchemy` but I don't imagine it will pass because it doesn't appear there's been typing tests on the current repo.
* `flask-sqlalchemy` has a `py-min` tox target and some `requirements-skip` files; do we need similar here? Not a thing I've seen elsewhere/am familiar with.

**Comment by Abdur-rahmaanJ** [comment]
@samuelhwilliams Thanks for taking up the PR.

1. Please branch in here to get feedback
2. Please use this as the reference https://github.com/pallets-eco/flask-debugtoolbar

**Comment by samuelhwilliams** [comment]
I don't have write access to this repo - I can't make a branch on here?

**Comment by Abdur-rahmaanJ** [comment]
@samuelhwilliams Oh just a normal WIP PR, thanks!
